name: Run Databricks Job on Push

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  run-databricks-job:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
      DATABRICKS_JOB_ID: '839156090872022'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Trigger Databricks Job
        id: trigger-job
        run: |
          # Trigger the job using the Databricks CLI
          # The --git-commit-hash option ensures the job uses the latest code
          databricks jobs run now ${{ env.DATABRICKS_JOB_ID }}
          echo "Job triggered"

      - name: Get run details
        id: get-run-details
        run: |
          RUN_ID=$(echo '${{ steps.trigger-job.outputs.run-id }}')
          echo "Run ID: $RUN_ID"
